### ISSUE TITLE
Wallpaper actions panel( layout at bottom ) needs to be visible properly

### ISSUE THREAD

**Issue by ronakpatel3110** [smartdevsgroup/wallpapers-ringtones-app#23] opened 2014-12-16 16:19 UTC
Please check view in "Premium HD wallpapers" app and make it same like that.

**Comment by Sandeep214** [comment] 2015-01-09 05:02
I guess, now all resolved for bottom layouts

**Comment by Sandeep214** [comment] 2015-01-09 05:03
closing this issue for now, re-open if the issue is not resolved from your point of view

**Closed** 2015-01-09 05:04 UTC
Labels: bug, resolved
